### ISSUE TITLE
Can't "zoom" one image products

### ISSUE THREAD

**Issue by pucilpet** [Oksydan/modern-prestashop-starter-theme#103]
If I have a product with just one image, nothing happens when clicking "zoom".

This is printed in the console:

Uncaught (in promise) TypeError: this.mainSliderSwiperInstance is null
    handleModalOpen ProductGallery.js:72

**Comment by Oksydan** [comment]
Hi @pucilpet,

I was able to reproduce an issue. 
I will come back to you when it will be fixed.

**Comment by Oksydan** [comment]
HI @pucilpet,

Issue has been fixed with this [commit](https://github.com/Oksydan/modern-prestashop-starter-theme/commit/3fdca09fe1e8171a0d40873d8486e94c01e02328).
It will be available in next minor release but you can fix it right now in your theme.

**Comment by Oksydan** [comment]
Hi @pucilpet,

new minor version has been [released](https://github.com/Oksydan/modern-prestashop-starter-theme/releases/tag/v2.2.1).
Thank you for your report.
