### ISSUE TITLE
Issue with Mailalert on out of stock product

### ISSUE THREAD

**Issue by Kandax86** [Oksydan/modern-prestashop-starter-theme#107]
Hi,
when you have a product with combinations in front, if you change de combination it reloads the entire add to cart block.
On first load no issue
But when you change combination the mailalert register button doesn't do the job anymore but try to add the product to cart instead by submitting the parent add to cart form.

I figured you did not use delegate on the clics events

so you may modify the JS of ps_emailalert module from:

`$('.js-mailalert-submit').on('click', function(e) {`

and 

`$('.js-remove-email-alert').on('click', function(e){`

**To**

`$(document).on('click','.js-mailalert-submit', function(e) {`

and 

`$(document).on('click','.js-remove-email-alert', function(e){`

so it register events even if the dom element is replaced.

Tell me if I'm not clear enough or if you have a better way to do this.

**Comment by Oksydan** [comment]
Hi @Kandax86,

thank you for your report. 
You are right, unfortunately whole `ps_emailalert` js/templates are poorly made 😕.
I will improve that whole js/my account page for that module.

The best solution will be showing dynamic fetched modal with form on clicking that notification button but it will required module modification. I am doing it this way, so you can even show it in listing page and allow customer to register.

**Comment by Oksydan** [comment]
Hi @Kandax86,

thank you for your report. 
Event register has been fixed. 
I wasn't aware that I already improved account page listing display.

BTW there is no need to delegate `'.js-remove-email-alert'` button, since it is only used in account page that isn't refreshed dynamically. 

Fix will be released with 2.3.0 version.

**Comment by Kandax86** [comment]
thanks
