### ISSUE TITLE
Install Issue : Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by mbensoussan** [Oksydan/modern-prestashop-starter-theme#108]
Hi,
i try yo install your template and i have 1 issue : 
what i do : 
i have make a unzip of source_code.zip of is_imageslider in /modules/is_imageslider (without branch name)
i have make a unzip of source_code.zip of is_searchbar in /modules/is_searchbar (without branch name)
i have make a unzip of source_code.zip of is_shoppingcart in /modules/is_shoppingcart(without branch name)
i have make a unzip of is_themecore.zip of is_themecore in/modules/is_themecore(without branch name)

i have make a unzip of modern-prestashop-starter-theme-v2.2.1.zip in themes/starter/

in ssh,
i make a composer install in /modules/is_themecore

in ssh, i make in themes/starter/_dev
npm install
npm run build
npm run dev

when i go in the backend of prestashop, i see the starter pack but when i try to activate i have this error : 

Install Issue : Trying to access array offset on value of type null
in [modules/ps_accounts/ps_accounts.php] (line 511)
Line 511.                'Error trying to PATCH shop : ' . $response['httpCode'] .

i'm not sure about the configuration of .env

i have put this where XXX is my domain name :
PORT=3505
SERVER_ADDRESS=dev.XXX.com
SITE_URL=https://dev.XXX.com
PUBLIC_PATH=/themes/starter/assets/

**Comment by mbensoussan** [comment]
when i run npm install, i have this information  : 

npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

18 vulnerabilities (3 moderate, 15 high)

next i try : npm audit report

ansi-regex  3.0.0 || 4.0.0 - 4.1.0 || 5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/eslint/node_modules/ansi-regex
node_modules/inquirer/node_modules/ansi-regex
node_modules/table/node_modules/ansi-regex
node_modules/yargs/node_modules/ansi-regex

glob-parent  <=5.1.1
Severity: high
Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
glob-parent before 6.0.1 and 5.1.2 vulnerable to Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-cj88-88mr-972w
fix available via `npm audit fix --force`
Will install stylelint@14.9.1, which is a breaking change
node_modules/stylelint/node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/stylelint/node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/stylelint/node_modules/globby
      stylelint  8.0.0 - 13.3.0
      Depends on vulnerable versions of globby
      Depends on vulnerable versions of meow
      Depends on vulnerable versions of postcss-markdown
      node_modules/stylelint
        stylelint-config-twbs-bootstrap  <=1.1.0
        Depends on vulnerable versions of stylelint
        node_modules/stylelint-config-twbs-bootstrap
          stylelint-config-prestashop  1.0.2 - 1.0.5
          Depends on vulnerable versions of stylelint-config-twbs-bootstrap
          node_modules/stylelint-config-prestashop

scss-tokenizer  *
Severity: high
Regular expression denial of service in scss-tokenizer - https://github.com/advisories/GHSA-7mwh-4pqv-wmr8
fix available via `npm audit fix --force`
Will install node-sass@4.5.3, which is a breaking change
node_modules/scss-tokenizer
  sass-graph  >=2.2.0
  Depends on vulnerable versions of scss-tokenizer
  node_modules/sass-graph
    node-sass  >=4.6.0
    Depends on vulnerable versions of sass-graph
    node_modules/node-sass

terser  >=5.0.0 <5.14.2 || <4.8.1
Severity: high
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS - https://github.com/advisories/GHSA-4wf5-vphf-c2xc
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS - https://github.com/advisories/GHSA-4wf5-vphf-c2xc
fix available via `npm audit fix`
node_modules/terser
node_modules/terser-webpack-plugin/node_modules/terser

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
fix available via `npm audit fix --force`
Will install stylelint@14.9.1, which is a breaking change
node_modules/trim
  remark-parse  <=8.0.3
  Depends on vulnerable versions of trim
  node_modules/remark-parse
    remark  5.0.0 - 12.0.1
    Depends on vulnerable versions of remark-parse
    node_modules/remark
      postcss-markdown  <=0.36.0
      Depends on vulnerable versions of remark
      node_modules/postcss-markdown

trim-newlines  <3.0.1
Severity: high
Uncontrolled Resource Consumption in trim-newlines - https://github.com/advisories/GHSA-7p7h-4mm5-852v
fix available via `npm audit fix --force`
Will install stylelint@14.9.1, which is a breaking change
node_modules/stylelint/node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  Depends on vulnerable versions of yargs-parser
  node_modules/stylelint/node_modules/meow

yargs-parser  6.0.0 - 13.1.1
Severity: moderate
Prototype Pollution in yargs-parser - https://github.com/advisories/GHSA-p9pc-299p-vxgp
fix available via `npm audit fix --force`
Will install stylelint@14.9.1, which is a breaking change
node_modules/stylelint/node_modules/yargs-parser

18 vulnerabilities (3 moderate, 15 high)

should i run npm audit fix ?

**Comment by Oksydan** [comment]
Hi @mbensoussan,

Install Issue : 

> Trying to access array offset on value of type null
> in [modules/ps_accounts/ps_accounts.php] (line 511)
> Line 511. 'Error trying to PAT
> CH shop : ' . $response['httpCode'] .

I am not touching it anywhere in code it might be issue related to that module. Try to change module folder name for now.

> i have put this where XXX is my domain name :
> PORT=3505
> SERVER_ADDRESS=dev.XXX.com
> SITE_URL=https://dev.xxx.com/
> PUBLIC_PATH=/themes/starter/assets/

Do you have your shop installation on remote server? 
`.env` file looks fine but remember to theme working properly in dev env you have to run webpack dev server or run build of your theme.

> npm WARN old lockfile
> npm WARN old lockfile The package-lock.json file was created with an old version of npm,

What is your node/npm version, recommended version from `.nvmrc` file which is 14.

> 18 vulnerabilities (3 moderate, 15 high)

All of those vulnerabilities I will try to fix in next version 2.3.0. It is also a reason why you shouldn't run your dev server on your remote machine.

**Comment by mbensoussan** [comment]
Hi, 
I confirm that when i delete the module PS_accounts, all seems to work perfect.

Futhermore, You should add in your notice installation that people don't have to forget to put this : (my first mistake)
composer install in /modules/is_themecore

Thank you.

**Comment by Oksydan** [comment]
Hi @mbensoussan,

I am aware of that missing installation step. 
BTW there is release package with required vendors already installed for is_themecore.

I will add this information to installation guide.

**Comment by Oksydan** [comment]
btw there is docs related issue https://github.com/Oksydan/modern-prestashop-starter-theme/issues/97.
If find something unclear or missing, leave a comment there so I can add this to my TODO list.
