### ISSUE TITLE
Repeated key on SwiperSlider.js

### ISSUE THREAD

**Issue by FranRomero** [Oksydan/modern-prestashop-starter-theme#109]
Hi!

I have noticed that on SwiperSlider.js file there is a key that is repeated twice in the object dynamicModulesMap. The key that is repeated is 'mousewheel' and I think the second one should be 'scrollbar' instead of 'mousewheel'.

Thanks in advance!

**Comment by Oksydan** [comment]
Hi @FranRomero,

You are right, thank you for your report.
I will inform you when it will be fixed.

**Comment by Oksydan** [comment]
Hi @FranRomero,

Problem has been fixed on develop branch.
Fix will be available in version 2.3.0.

Thank you for your contribution.

**Comment by Oksydan** [comment]
Hi @FranRomero,

new version has been released. 
I am closing this issue. 
Thank you for your contribution.
