### ISSUE TITLE
compilation on web server

### ISSUE THREAD

**Issue by Blaaszkovsky** [Oksydan/modern-prestashop-starter-theme#110]
Hi Igor, how can I disable the function that is responsible for redirecting to BO etc. I work on my server and domain with node.js, but I have the following errors, probably related to the fact that the server does not have to listen for this.

`95% emitting emit(node:3848) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use node --trace-deprecation ... to show where the warning was created)
99% done plugins webpack-bundle-analyzerevents.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EPERM: operation not permitted 127.0.0.1:8888
    at Server.setupListenHandle [as _listen2] (net.js:1314:21)
    at listenInCluster (net.js:1379:12)
    at doListen (net.js:1516:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EPERM',
  errno: -1,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8888
}`

**Comment by Oksydan** [comment]
Hi @Blaaszkovsky 

What script are you running? 
What is your version of node/npm?

**Comment by Blaaszkovsky** [comment]
node: v14.20.0
npm: 6.14.8

One problem I already solved, I didn't have the port to the server unlocked, so it didn't work. However, now another problem has surfaced, the watch option on hosting is completely not working. It seems to compile files the first time with "npm run dev", but nothing is done when changing.

https://pastebin.com/isipC2kL

**Comment by Blaaszkovsky** [comment]
I also did not add that after the changes in devserver's config, I have this error with your configuration: https://pastebin.com/ay9eFbit

**Comment by Blaaszkovsky** [comment]
I even tried to add `usePolling: true` to the dev server option to force the changes, but unfortunately I can't see the files at all.

**Comment by Oksydan** [comment]
What is your vhost configuration and .env file?

**Comment by Oksydan** [comment]
Hi @Blaaszkovsky,

Some changes has been made to CLI scripts: 
- watch option has been added,
- bundle analyzer has been removed from `build` script and moved to `build-analyze` script,
- `build` script right now have silent output to reduce terminal pollution (only display errors), useful when building on remote server. 

It will be available in next version 2.3.0, you can check it out https://github.com/Oksydan/modern-prestashop-starter-theme/commit/a16395e8b6ce4c11cc78afd0658239f59f699d5b.

**Comment by Oksydan** [comment]
Hi @Blaaszkovsky ,

new version has been released. 
I am closing this issue. 
Thank you for your contribution.
