### ISSUE TITLE
error that I dont know what will impact with cause I cant understand any ideas ?? 

### ISSUE THREAD

**Issue by afrixea** [Oksydan/modern-prestashop-starter-theme#111]
Uncaught TypeError: Cannot read properties of null (reading 'append')
    at product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:127:346
    at NodeList.forEach (<anonymous>)
    at a (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:127:72)
    at 433 (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:127:361)
    at a (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:1:583)
    at 432 (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:109:26427)
    at a (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:1:583)
    at r (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:1:444)
    at Array.e [as push] (product.bundle.js?v=6ea9ab1baa0efb9e19094440c317e21b:1:307)
    at vendors.js?v=6ea9ab1baa0efb9e19094440c317e21b:1:59
    
![image](https://user-images.githubusercontent.com/45628994/184498722-6f0bd6d2-045b-4a64-9ca0-2d6bad160152.png)
![image](https://user-images.githubusercontent.com/45628994/184498736-db1c35e5-bf59-4ec5-9f89-9b8360ec5590.png)

Im gonna try and fix this myself but maybe you have any idea what scripts I should be looking on since this is a compiled script with  the error or ? maybe you know what is causing that ???
.....and  I had another error that everything in php was loaded so you could see the products skeleton  but no images or filters where loaded  no jquery existed("loaded" ) there was an error saying prestashop is not defined in this place in the <head>
![image](https://user-images.githubusercontent.com/45628994/184498872-c9d890fb-3d65-496e-990d-d290fd3151bd.png)

and 

after I regen the .htaccess I cant find the same problem again or I  just cant find the same links that had this problem cause it didnt happened in every category but only in some so I dont know why and how but this exist as well

Im writing this maybe you already know something and if you dont its ok I will fix those and I will give the scripts...
1 more.. ajax search bar is not working in safari so I will change that with API and AXIOS

**Comment by afrixea** [comment]
OHHH and I forgot WISHLIST its not working should it be working??? or I messed up something ???

**Comment by Oksydan** [comment]
Hi @afrixea 
Wiashlist module isn't supported. I will provide simple wishlist/favorite module "soon"

**Comment by Oksydan** [comment]
Hi @afrixea, 

I am closing this issue. I don't want to make blockwishlist module working with this starter but you can do it on your own.

**Comment by afrixea** [comment]
this was not about the blocklist read !! I sent an error that have to do with product.bundle.js

**Comment by Oksydan** [comment]
Hi @afrixea,

product bundle is wishlist asset not starter. 
Problem is related to wishlist module, you can modify it on your own or find alternative (recommended)
