### ISSUE TITLE
Vendor prefixed property -webkit-sticky

### ISSUE THREAD

**Issue by przemokon** [Oksydan/modern-prestashop-starter-theme#112]
Hello,

I found that adding css property: ```position: -webkit-sticky``` have no effect on builded files.
I think that this is because of webpack configuration, but i can't find the reason.

What i checked:

PurgeCSS comments:
```/* purgecss start ignore */```
```/* purgecss end ignore */```
also
```/*! purgecss start ignore */```
```/*! purgecss end ignore */```

This property is required by Safari browsers 7.1-12.1: [Can I Use](https://caniuse.com/?search=position%3Asticky)

Is there any possibility to add this CSS rule?

**Comment by Oksydan** [comment]
Hi @przemokon 

We are using default browserslist from autoprefixer which is `> 0.5%, last 2 versions, Firefox ESR, not dead`. 
That Safari usage is below 0.5% according to caniuse 0.11% that why this prefix is being removed automatically. 
You can use your own browslerlist if you want. Quick guide how https://github.com/browserslist/browserslist#config-file

**Comment by przemokon** [comment]
Allright, thanks for response
