### ISSUE TITLE
Refresh slider after category pagination (on updateFacets)

### ISSUE THREAD

**Issue by augustomurri** [Oksydan/modern-prestashop-starter-theme#114]
Hi, i don't know how to handle this problem / bug
I use a Swiper carousel for show subcategories, but when i click on pagination it is reinitialized
You can try it here [https://nuovo.tsunaminutrition.it/13-perdita-di-peso](https://nuovo.tsunaminutrition.it/13-perdita-di-peso)

I tried to add something like this in js/listing.js

`
  const slider = new PageSlider({
    slidesPerView: 1,
  });

  prestashop.on('updatedProductList', () => {
    prestashop.pageLazyLoad.update();
    productListingComments.init();
    productListingComments.load();
    slider.init();
    slider.refresh();
  });

`

**Comment by Oksydan** [comment]
Hi @augustomurri,

what is your starter version?

**Comment by augustomurri** [comment]
name: master
display_name: master
version: 1.0.0

**Comment by Oksydan** [comment]
Are you sure that's real version? Check package.json file. Theme.yml might be modified by you.

**Comment by augustomurri** [comment]
{
  "name": "modern-prestashop-build-tool",
  "version": "2.1.0",
  "description": "Modern tools that help you develop your theme.",
  "main": "index.js",
  "scripts": {
    "build-purge": "webpack --progress --mode=production --purge=true",
    "build": "webpack --progress --mode=production",
    "watch": "npm run dev",
    "dev": "webpack serve --progress --mode=development",
    "scss-fix": "stylelint \"**/*.scss\" --fix",
    "eslint-fix": "eslint \"**/*.js\" --fix"
  }

**Comment by Oksydan** [comment]
Hi @augustomurri,

open `_dev/js/components/sliders.js` and adds there.

```js
  prestashop.on('updatedProductList', () => {
    slider.refresh();
  });
```

**Comment by augustomurri** [comment]
Hi @Oksydan , super.. thanks

**Comment by Oksydan** [comment]
I am closing this issue.

If you will be using newer version it is much simpler. 
You have to run just `prestashop.pageSlider.refresh()` anywhere in your code.
If you want to know more about how to use `PageSlider` class I wrote documentation section about it.
