### ISSUE TITLE
Facets search by second level subcategory does not work

### ISSUE THREAD

**Issue by FranRomero** [Oksydan/modern-prestashop-starter-theme#124]
Hi!
I am trying to make a search by second level subcategory but does not seem to work. What I mean for second level subcategory is the following:

Clothes 
     -> Men (First level subcategory, pending from Clothes)
            ----> Child (Second level subcategory, pending from Men)

What I am doing: 
- Installing a cleaning Prestashop v1.7.8.7 with demo data
- By default, it gives to you only 1 level of subcategory for example Clothes > Men so I have created a new pending category for Men called "Child" and I have added some products to it, similar to the previous schema.
- I have configured "Category filter depth" to 0 on "Faceted Search" module to do not have limit on category filter and added the new category on the template.
- Also indexed all mixing prices, rebuild entire price index, build attributes and features indexes and clear caché from "Faceted Search" module.

Now I go to the front:
If I go to Clothes section, it let me filter by "Men" but not by "Child". Only lets me filter by first level subcategory, like "Men" or "Women", but if I go to "Men" section, it lets me filter by "Child", because right now "Child" its first level subcategory from "Men".

---------------------------------------------------------
Other configuration that can be useful to reproduce it:
- Faceted Search module v3.8.0
- Node v14.19.3
- PHP v7.4

**Comment by Oksydan** [comment]
HI @FranRomero,

I am sorry for a delay. 
Yes, I was able to reproduce an issue. 
You should create an issue in [prestashop project ](https://github.com/PrestaShop/PrestaShop). 
It's prestashop native module feature request tbh.

I am closing this issue if you find any problem/feature request for this project fell free to create new issue.

**Comment by FranRomero** [comment]
Sorry @Oksydan. I have added the issue to prestashop project github.

Thanks anyway and my apologies!!
