### ISSUE TITLE
issue with first installation

### ISSUE THREAD

**Issue by lucaange** [Oksydan/modern-prestashop-starter-theme#134]
Hi everyone I am new in modern-prestashop-starter theme
I have followed the installation guide but I don't see the materials icons locally and I have the follow error
Where is the problems=?

![errorr](https://user-images.githubusercontent.com/34936657/196812070-54d5f412-90e3-431a-9b86-d57cbb05841e.jpg)

**Comment by lucaange** [comment]
I think I have with vhost configuration
Anyone have such guide?

**Comment by Oksydan** [comment]
Hi @lucaange,

Looks like you are not using vhosts for your local environment. 
Consider using vhosts or use just watch command instead of dev. 

BTW what is your shop url and `.env` file configuration?

**Comment by lucaange** [comment]
I have solved by an exact configuration of vhost and xampp
