### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by lucaange** [Oksydan/modern-prestashop-starter-theme#135]
hi everyone I am new in starter theme
I have installed step by step modern starter theme 
But the theme have the follow error with prestashop 1.7.8
`Uncaught TypeError: Cannot read properties of null (reading 'append')
    at product.bundle.js?v=eccbc87e4b5ce2fe28308fd9f2a7baf3:127:346`

did I do something wrong?

**Comment by Oksydan** [comment]
Hi @lucaange 
Error is related to blockwishlist module https://github.com/Oksydan/modern-prestashop-starter-theme/issues/53.
This module is not supported. I recommend to disable this module or adjust it by yourself.
