### ISSUE TITLE
Error: is_themecore contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by Michal41** [Oksydan/modern-prestashop-starter-theme#140]
Hello, i have problem with installation. is_themcore module

following error:

Error: Class Oksydan\Module\IsThemeCore\Form\Settings\GeneralConfiguration contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PrestaShop\PrestaShop\Core\Configuration\AbstractMultistoreConfiguration::buildResolver)

**Comment by Oksydan** [comment]
Hi @Michal41,

This problem is related to changes in prestashop 8.0. Starter isn't ready for prestashop 8.0 yet. Most of the work is already done but on develop branches. New version should be released in two weeks.

**Comment by Michal41** [comment]
Thank you !
i have downgraded prestashop version and all works now
