### ISSUE TITLE
Add modules required

### ISSUE THREAD

**Issue by PululuK** [Oksydan/modern-prestashop-starter-theme#17]
During installation I have some errors, because some required modules is missing.

- is_imageslider
- is_searchbar
- is_shoppingcart
- is_themecore

We nee to alert people in requirements doc.

**Comment by Oksydan** [comment]
Hi,
package from [releases](https://github.com/Oksydan/modern-prestashop-starter-theme/releases/tag/v1.0.0) contains these modules.

**Comment by PululuK** [comment]
> Hi,
> package from [releases](https://github.com/Oksydan/modern-prestashop-starter-theme/releases/tag/v1.0.0) contains these modules.

Hi @Oksydan 
Yes ... but it missing in manual install process !

**Comment by Oksydan** [comment]
@PululuK 
Yes, you are right. Could you make pull request on `develop` branch? I will update contribution guide later.

**Comment by PululuK** [comment]
Yep !
I just rebase my PR https://github.com/Oksydan/modern-prestashop-starter-theme/pull/18

**Comment by Oksydan** [comment]
@PululuK 
The changes have been merged. Thank you again.
