### ISSUE TITLE
🐛 [BUG] - Search result ajax responsive

### ISSUE THREAD

**Issue by ytilotti** [Oksydan/modern-prestashop-starter-theme#178]
### Description

The search result ajax is not showing correctly between 720px and 960px.

After 960px:
![image](https://user-images.githubusercontent.com/5848945/214261894-64a3fd90-f30e-48cd-82a1-4e16dd4a8a64.png)

After 720px:
![image](https://user-images.githubusercontent.com/5848945/214262041-1479ce55-884b-4eda-83e0-e85398387c29.png)

### Node.js version

v14.21

### php version

v7.4

### OS and it's version

Docker

### Browsers

Chrome

### Required module/theme

is_searchbar/theme v3

### Reproduction steps

```bash
1. Go to front office
2. Search in the bar
3. Resize the page
```

**Comment by Oksydan** [comment]
Hi @ytilotti,

thank you for your issue and PR.
I was able to reproduce an issue.

**Comment by Oksydan** [comment]
Hi @ytilotti,

new version has been released.
Thank you for your contribution.
