### ISSUE TITLE
Implementation of json-ld from 1.7.8 of Classic

### ISSUE THREAD

**Issue by kpodemski** [Oksydan/modern-prestashop-starter-theme#20]
Maybe it would be good to use json-ld implementation from 1.7.8 and classic?

https://github.com/PrestaShop/PrestaShop/pull/23151

**Comment by Oksydan** [comment]
Hi @kpodemski,
Json-ld data is handled inside [is_themecore](https://github.com/Oksydan/is_themecore) module and I am not going to change it.
Thank you for your suggestion.
