### ISSUE TITLE
🚀 [REQUEST] - Product quantity on product card & sync with cart

### ISSUE THREAD

**Issue by ffixitt** [Oksydan/modern-prestashop-starter-theme#200]
### Summary

[![product-qt.gif](https://s2.gifyu.com/images/product-qt.gif)](https://gifyu.com/image/S7Bjk)

### Feature target required module/theme

theme

### Drawbacks

UX practices ...

**Comment by Oksydan** [comment]
Hi @quddoss,

thank you for creating an issue.
Unfortunately this feature won't fit every merchant need. 
It's starter theme and we don't want to force any extra unneeded features.
