### ISSUE TITLE
🐛 [BUG] - Compiled theme doesn't allow ajax cart

### ISSUE THREAD

**Issue by piotrszpruta** [Oksydan/modern-prestashop-starter-theme#407]
### Description

Hello, I've compiled the plain theme using `yarn build` following all steps in the instructions and while adding product to cart it loads infinitely without modal popup. I've tried many things but can't settle this up. After page refresh it updates.
![image](https://github.com/Oksydan/falcon/assets/38475451/f93f2390-68b0-46af-a423-9223057b66f4)
That's how cart is seen.
Provided node version is yarn version

### Node.js version

1.22.22

### php version

8.2

### OS and it's version

Windows

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Install theme using steps in github readme
2. Go to _dev and build using yarn.
3. Push update to server
4. Refresh page and try adding to cart
```

**Comment by Oksydan** [comment]
Hi @piotrszpruta,

thank you for creating an issue.
Prestashop isn't compatible with php version 8.2 - you can read more about it [here](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart)
Node version 1.22.22 is not the correct version of node - it may be the yarn version. You can run `node -v` in the terminal to check the node.js version. 
I wasn't able to reproduce an issue. Try to downgrade your php version to 8.1 and check it out again 😉. You can also provide more information - error logs, browser console.

**Comment by piotrszpruta** [comment]
> Hi @piotrszpruta,
> 
> thank you for creating an issue. Prestashop isn't compatible with php version 8.2 - you can read more about it [here](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart) Node version 1.22.22 is not the correct version of node - it may be the yarn version. You can run `node -v` in the terminal to check the node.js version. I wasn't able to reproduce an issue. Try to downgrade your php version to 8.1 and check it out again 😉. You can also provide more information - error logs, browser console.

Hello, thank you for the response.
I've tried changing php version to 8.1, I've cleared cache and it doesn't change anything. 
Yes its yarn version, node version is v18.20.2.
Sadly no errors in logs and browser console.

**Comment by Oksydan** [comment]
Hi,

Can you check your network tab in the browser? On add to cart there should be one call to prestashop cart controller. Then on updateCart there should be another call to is_shoppingcart controller.
I need more information, I won't be able to help you. Besides it's 100% your env problem 😕

**Comment by Oksydan** [comment]
Hi @piotrszpruta,

As we have not received any information from you in a month, I am closing this issue.
Feel free to open new one.
