### ISSUE TITLE
🐛 [BUG] - Unable to place order with official stripe module on mobile devices

### ISSUE THREAD

**Issue by stigmi-man** [Oksydan/modern-prestashop-starter-theme#408]
### Description

With the official Stripe module and the following configuration:
![image](https://github.com/Oksydan/falcon/assets/45425264/83b6e95c-06d8-407a-8980-8d3d1ec9be17)

**When placing an order on a mobile device, the page refreshes, and we cannot proceed to the next step.**

The issue arises because there are two buttons in the `templates\checkout\_partials\steps\payment.tpl` file:
![image](https://github.com/Oksydan/falcon/assets/45425264/5fd6cca1-2953-4d88-ad91-84559c66314c)
The Stripe JavaScript code adds an event listener to the first button only, causing the second button to malfunction on mobile devices.

Would it not be cleaner and more efficient to keep only a single button in the payment template? This approach would ensure consistent behavior across all devices and eliminate the issue caused by the presence of multiple buttons.

### Node.js version

v14.1.0

### php version

v7.4

### OS and it's version

Windows

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
0. Install and configure the Stripe Official module v3.2.2
   -> Select "Integrated payment form"
      Payment Form Layout : "Accordion without radio buttons"
      Payment Form Position : "With the Prestashop payment methods" 
      Select a theme for the integrated payment form : "Stripe"

On Mobile :
1. Add a product to the cart
2. Process checkout
3. Use a strip payment
4. Click on the "Place order" Button
```

**Comment by Oksydan** [comment]
Hi @stigmi-man,

we might consider implementing this in Falcon 4 but I can't promise anything ATM. 
TBH it's stripe module mistake, the module developers should handle this case better. 
I am closing this issue. Feel free to open new one.
