### ISSUE TITLE
🐛 [BUG] - problem with the children's theme

### ISSUE THREAD

**Issue by jbbrabec** [Oksydan/modern-prestashop-starter-theme#410]
### Description

When I create a child theme following the instructions 
[https://devdocs.prestashop-project.org/8/themes/reference/template-inheritance/parent-child-feature/](url)

a lot of things don't work. It doesn't work to display price by attribute, some images don't show, description or parameters don't show ...

theme/child_falcon/config/theme.yml
`parent: falcon
name: child_falcon
display_name: Child theme of falcon's theme
version: 0.0.1
assets:
  use_parent_assets: true`

Do I need to build this child theme somehow?

### Node.js version

16.20.2

### php version

8.1.28

### OS and it's version

Linux

### Browsers

Chrome

### Required module/theme

is_themecore, theme

### Reproduction steps

```bash
1. create a child theme
```

**Comment by Oksydan** [comment]
Hi @jbbrabec 

child theme feature isn't supported in Falcon < 4. We plan to support this feature in version 4 😉.
I am closing this issue to reopen or create a new one.
