### ISSUE TITLE
🐛 [BUG] - Ajax cart doesn't work

### ISSUE THREAD

**Issue by sikl0** [Oksydan/modern-prestashop-starter-theme#418]
### Description

Hello, I noticed that my cart isn't working as it should. When I try to add something to cart, confirmations modal doesn't appear and quantity of items on cart icon doesn't change. When I click the cart icon it shows only this:
![image](https://github.com/Oksydan/falcon/assets/45985086/f4338574-4d26-404a-ba7b-6a3c289145aa)

The button actually is adding the product to the cart because after page refresh there are added products in cart.
I referred to the issue #407 and  checked what's happening in the network tab:
![image](https://github.com/Oksydan/falcon/assets/45985086/756820f1-99df-449a-88fc-b30eee8c1c3e)

As you can see there's no `ajax` fetch in here and any images for modal result like on your demo:
![image](https://github.com/Oksydan/falcon/assets/45985086/3ba1ec84-64a6-49df-9985-80785b7f1fec)

### Node.js version

16.20.2

### php version

8.1

### OS and it's version

Linux

### Browsers

Chrome

### Required module/theme

is_shoppingcart

### Reproduction steps

```bash
1. Install theme using steps in github readme including installing required modules with correct versions
2. Go to _dev, install using npm, create .env by project-init, then run build.
3. Enable ajax cart in is_shoppingcart module.
4. Go to FO and try to add any product to the cart.
```

**Comment by Oksydan** [comment]
Hi @sikl0,

unfortunately I wasn't able to reproduce an issue.
Could you please show me what's the response form module /ajax endpoint?

**Comment by sikl0** [comment]
Hi @Oksydan,
I figured out that the problem was I was building only theme without the modules with correct path. After reproducing path on local node.js server and building the theme everything is fine now.

**Comment by Oksydan** [comment]
Hi @sikl0,

sine this problem has been solved I am closing this issue.
Feel free to open new one.
