### ISSUE TITLE
🚀 [REQUEST] - <title>Support for 8.2.X

### ISSUE THREAD

**Issue by JakubDudzak** [Oksydan/modern-prestashop-starter-theme#426]
### Summary

Hello, are you planning to support prestashop 8.2.X? Can you see any potential issues when using this version (officially supporting 8.0.X), or I should stick with 8.0.X for now? Has anyone tested newer versions for this theme? Thank you

### Feature target required module/theme

theme

### Drawbacks

requires testing

**Comment by Oksydan** [comment]
Hi @JakubDudzak 

the theme is working properly with Prestashop 8.0, 8.1 and 8.2 😉. 
It's just misleading sentence in the docs 😕

**Comment by Oksydan** [comment]
Hi @JakubDudzak,

I am closing this issue. Feel free to open new one 😉
