### ISSUE TITLE
🐛 [BUG] - No searchbar, nor cart buttons when no categories are present

### ISSUE THREAD

**Issue by JakubDudzak** [Oksydan/modern-prestashop-starter-theme#427]
### Description

It really confused me when I did a fresh install without dummy categories, when I added new dummy category, the problem fixed itself. This problem may not be worth fixing, but instead adding at least one category to requirements to work properly.

### Node.js version

v18.20.3

### php version

v8.1

### OS and it's version

Windows 10

### Browsers

Firefox

### Required module/theme

theme

### Reproduction steps

```bash
1. Install fresh prestashop without categories, along with theme and modules
2. On a FO, see no searchbar, nor cart button
```

**Comment by Oksydan** [comment]
Hi @JakubDudzak 

It's strange indeed. I didn't test it 🤔 but it might be related to "catalog mode"? When there is no category in the store 🤔 
Yes, I think that it not worth fixing since store can't exist w/o category 🤔 

I am closing this issue. Feel free to reopen
