### ISSUE TITLE
🐛 [BUG] - Upgrade file name - Module is_themecore

### ISSUE THREAD

**Issue by cdigruttola** [Oksydan/modern-prestashop-starter-theme#430]
### Description

Hi,
the filenames for the upgrades are wrong. For example a name is upgrade-4-1-2.php but according to Prestashop the name should be upgrade-4.1.2.php

### Node.js version

v18

### php version

8.1, 7.4

### OS and it's version

MacOs

### Required module/theme

is_themecore

### Reproduction steps

```bash
Upgrade module doesn't register the module to the hook.
Please refer to https://devdocs.prestashop-project.org/8/modules/creation/enabling-auto-update/ for the naming convention
```

**Comment by Oksydan** [comment]
Hi @cdigruttola,

How could I have missed it 😱 
New version has been released https://github.com/Oksydan/is_themecore/releases/tag/v4.1.3. Please check it out 🥶
