### ISSUE TITLE
🐛 [BUG] - Pickup points from module "DPD France" (and possibly others) not displayed correctly

### ISSUE THREAD

**Issue by hugo-fasone** [Oksydan/modern-prestashop-starter-theme#431]
### Description

The "DPD France" module (https://addons.prestashop.com/fr/transporteurs/19414-dpd-france.html) injects in the DOM its pickup points using the class "delivery-option" on the shipping step of the checkout page. The class "delivery-option" is in the classic theme (https://github.com/PrestaShop/classic-theme/blob/efb5fa7aa2ca2fb856d5f38b720fb6d39f448526/templates/checkout/_partials/steps/shipping.tpl#L44C35-L44C50) but not in Falcon theme, this issue may not be specific to the "DPD France" module, other modules could possibly use this class in their JS for exemple

Since the class "delivery-option" does not exist, the pickup points are injected below the "Continue" button, which is not inuitive at all.

The fix is to add the class "delivery-option" on the delivery options

### Node.js version

N/A

### php version

N/A

### OS and it's version

N/A

### Required module/theme

theme

### Reproduction steps

```bash
1. Install DPD France module 
2. Configure it so the "Pickup" delivery option is available
3. Go to the "delivery" step of the checkout and see that the pickup points are not showed correctly
```

**Comment by hugo-fasone** [comment]
Fixed by https://github.com/Oksydan/falcon/pull/432

**Comment by Oksydan** [comment]
Hi @hugo-fasone,

thank you for creating an issue and contribution.
You might be right but modules should relay on `js-delivery-option` class instead of `delivery-option` class but I know that not every theme has implemented `js-` prefixed class properly 😢

**Comment by Oksydan** [comment]
Changes has been merged into develop. 
I am closing this issue 😉. Thank you for your contribution.
