### ISSUE TITLE
Smarty Exception on order confirmation

### ISSUE THREAD

**Issue by a-pare** [Oksydan/modern-prestashop-starter-theme#50]
#### Describe the bug

After validating an order, a smarty exception is thrown on the order confirmation page. 

#### Steps to Reproduce

1. Got to FO
2. Identify you as a customer
3. Add a product to cart and go at the end of the checkout
4. After validating your order, an exception is thrown.

The error is explicit, an operator is missing between the first condition `$order.subtotals !== null` and the second one `$order.subtotals.tax.label !== null`. After adding the operator || (or &, depends of what you expect) in the file /templates/checkout/order-confirmation.tpl, line 110, the page is displayed as expected :) 

**Screenshots**

<img width="2043" alt="Capture d’écran 2021-10-27 à 15 50 01" src="https://user-images.githubusercontent.com/92056140/139079731-100206aa-cb35-4903-8ddf-0c24ea86e301.png">

#### Additional information

* Starter Theme version: 2.0.0
* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by Oksydan** [comment]
Hi @a-pare,
I was able to reproduce an issue. 
Thank you for your report.

**Comment by Oksydan** [comment]
@a-pare thank you once more for report

**Comment by Oksydan** [comment]
Fixed by https://github.com/Oksydan/modern-prestashop-starter-theme/pull/52
