### ISSUE TITLE
Problem with lazy loading duplicated image in imageslider module

### ISSUE THREAD

**Issue by diseneopl** [Oksydan/modern-prestashop-starter-theme#54]
Sometimes when on first slide click prev arrow, image isn't load and background is gray. Tested on demo. This most often occurs after returning to the home page from another page.

**Comment by Oksydan** [comment]
fixed with starter [v2.0.1](https://github.com/Oksydan/modern-prestashop-starter-theme/releases/tag/v2.0.1) version
and latest [slider module](https://github.com/Oksydan/is_imageslider/releases/tag/v1.0.3) version
