### ISSUE TITLE
A bug will appear when you click to hide/show password on the checkout page

### ISSUE THREAD

**Issue by chrislais** [Oksydan/modern-prestashop-starter-theme#58]
![20211209001623](https://user-images.githubusercontent.com/65403988/145244356-25d25ff1-4b23-4589-8360-bbaa2c073666.png)

**Comment by chrislais** [comment]
![20211209001633](https://user-images.githubusercontent.com/65403988/145244864-aa04cf9d-f2a4-4b71-8574-851718d58263.png)

**Comment by Oksydan** [comment]
Hi @chrislais,
I manage to reproduce problem and fix it.
Fix will be introduced in next release. 
You can fix it now in your theme by implementing this fix https://github.com/Oksydan/modern-prestashop-starter-theme/commit/cef75402fae99ed00f80bccbbb7fb461b2b82895
