### ISSUE TITLE
Issue with horizontal menu - overflow right

### ISSUE THREAD

**Issue by stephR** [Oksydan/modern-prestashop-starter-theme#59]
Hi

When more than few items (>4) in the N+1 subcategories, the items list in the header horizontal menu creates an x-axis overflow on the page.

**Comment by Oksydan** [comment]
Hi @stephR,
I manage to reproduce problem and fix it.
You can now implement it into your theme by adding changes from this commit https://github.com/Oksydan/modern-prestashop-starter-theme/commit/e8d15fbf9a5454aeafd5feb6230c435b7259ca93.
Fix will be available in next release.
