### ISSUE TITLE
Combination images not refreshing on quick view

### ISSUE THREAD

**Issue by daresh** [Oksydan/modern-prestashop-starter-theme#63]
When quick viewing a product with images assigned to combinations, the image is not refreshed after selecting a combination.

For example - Hummingbird printed t-shirt, changed from white to black in the quick view popup.

**Comment by Oksydan** [comment]
Hi @daresh,
thank you for your report.
I was able to reproduce the problem and fix it.
Fix is available [here](https://github.com/Oksydan/modern-prestashop-starter-theme/commit/d1d6257c422bde49fcc44a7d0f8e174673df8b1a) and you can fix it in you project right now.
It will be released with next version.

I am closing this issue. If you applied that changes and still facing the problem reopen this issue or create another one.

**Comment by daresh** [comment]
Thanks a lot for a quick fix! :)
