### ISSUE TITLE
lots of white space at the top of the page in front office

### ISSUE THREAD

**Issue by kennethbruyninckx** [Oksydan/modern-prestashop-starter-theme#67]
PS 1.7.8.2 (fresh install nothing added/changed except for the starter theme)
PHP 7.3.29
starter theme 2.0.2
is_imageslider-1.0.4
is_searchbar-1.0.0
is_shoppingcart-1.0.0
is_themecore-1.1.2

View of front office with classic theme (no white space at the top of the page):

![image](https://user-images.githubusercontent.com/63542736/147987989-92672da4-98ff-4716-b6ae-b7985647b5c0.png)

Changed theme from classic to starter & cleared cache from back office.
View of front office with starter theme (notice that the scroll bar on the right is half way the browser window!):

![image](https://user-images.githubusercontent.com/63542736/147988429-f5ce8a79-ee2b-4956-82af-4e76fa36fadc.png)

If you scroll up you see the enormous amount of white space:

![image](https://user-images.githubusercontent.com/63542736/147988583-218449c1-328e-4378-bc8e-c4b9ae22fe56.png)

**Comment by Oksydan** [comment]
Hi @kennethbruyninckx,
thank you for your report. 
It is actually duplicated issue https://github.com/Oksydan/modern-prestashop-starter-theme/issues/53
You have to remove/disable native blockwishlist module.
I am closing this issue, if you find any problem create new issue.
