### ISSUE TITLE
Notice: Trying to access array offset on value of type bool (PHP 7.4 is_shoppingcart override)

### ISSUE THREAD

**Issue by lramos-prolaser** [Oksydan/modern-prestashop-starter-theme#70]
Hello!
There is a missing `{if $product.default_image}` control in `starter/modules/is_shoppingcart/views/template/front/is_shoppingcart-product-line.tpl` 

![image](https://user-images.githubusercontent.com/90182741/151820143-48446abc-1ad1-43e4-b3ff-b7c43943b635.png)

For any of you having this same problem, there's a quick fix waiting for the next release of the theme with these bugs fixed, (as announced by @Oksydan [here](https://github.com/Oksydan/modern-prestashop-starter-theme/issues/66#issuecomment-1012545620) and [here](https://github.com/Oksydan/is_shoppingcart/issues/3#issuecomment-999167608) ):

In theme's directory `starter/modules/is_shoppingcart/views/template/front/is_shoppingcart-product-line.tpl` change these lines:
```
        <img
            {generateImagesSources image=$product.default_image size='cart_default' lazyload=false}
            alt="{$product.name|escape:'quotes'}"
            class="img-fluid"
            width="{$product.default_image.bySize.cart_default.width}"
            height="{$product.default_image.bySize.cart_default.height}">
```
to:
```
        <img
            {if $product.default_image}
                {generateImagesSources image=$product.default_image size='cart_default' lazyload=false}
            {else}
                src="{$urls.no_picture_image.bySize.cart_default.url}"
            {/if}
            alt="{$product.name|escape:'quotes'}"
            class="img-fluid"
            width="{if !empty($product.default_image)}{$product.default_image.bySize.cart_default.width}{/if}"
            height="{if !empty($product.default_image)}{$product.default_image.bySize.cart_default.height}{/if}">
```

**Comment by Oksydan** [comment]
Hi @lramos-prolaser,
thank you for your report.
I know that next version is a bit late. I promise next version by the end of the month.

**Comment by Oksydan** [comment]
Hi @lramos-prolaser,
fix has been applied. It is already on develop branch. 
New minor release will be soon.
