### ISSUE TITLE
Typo in translation line

### ISSUE THREAD

**Issue by lramos-prolaser** [Oksydan/modern-prestashop-starter-theme#73]
Hello!
I found a typo in the translation line in [catalog/_partials/per-page.tpl](https://github.com/Oksydan/modern-prestashop-starter-theme/blob/0cb14a96c8bccb501eb2dd92a255ea050e916acf/templates/catalog/_partials/per-page.tpl). I was not able to translate "Per page:", so I changed

```{l s='Per page:' l='Shop.Theme.Catalog'}```
to 
```{l s='Per page:' d='Shop.Theme.Catalog'}```

Just change the `l` and replace it by `d`

**Comment by lramos-prolaser** [comment]
There's also another typo in this file: `currentUrlFromated` instead of `currentUrlFormated`

**Comment by Oksydan** [comment]
Hi @lramos-prolaser, 
fix merged to develop branch thank you.
