### ISSUE TITLE
Notice when debug active on product page

### ISSUE THREAD

**Issue by Kandax86** [Oksydan/modern-prestashop-starter-theme#76]
Hello it seems that productcomments module create a Notice failure on product page when debug is active

I fixed this by editing modules/productcomments/views/templates/hook/product-comments-list.tpl
i replaced: 
line 49
data-comment-item-prototype="{$comment_prototype|escape:'html_attr'}">
by
data-comment-item-prototype="{$comment_prototype}">
the error was
User Notice: escape: unsupported type: html_attr - returning unmodified string
i don't know if there is an other way to cleanup the string or to avoid this notice if nothing is cleaned.

Thank you.

**Comment by Oksydan** [comment]
Hi @Kandax86
thank you for your report.
Fix has been added to develop branch and new minor version will be released soon
