### ISSUE TITLE
Fix shop logo url in maintenance.tpl

### ISSUE THREAD

**Issue by lucrp** [Oksydan/modern-prestashop-starter-theme#79]
Hello,

When shop is in maintenance, logo is not displayed. 

I fixed it replacing 
```
<img src="{$urls.img_ps_url}{$shop.logo}" alt="logo" loading="lazy">
```
by just `{$shop.logo}`
```
<img src="{$shop.logo}" alt="logo" loading="lazy">
```
in `maintenance.tpl`

**Comment by Oksydan** [comment]
Hi @lucrp 
Thank you for your contribution.
