### ISSUE TITLE
Mobile version lazy load problem. 

### ISSUE THREAD

**Issue by slawekmoskal** [Oksydan/modern-prestashop-starter-theme#81]
I have a problem with the first photos in the product list. are invisible. after refreshing you can see them. when you go to the next page, the first few photos are always invisible. Your demo has the same problem.

iOS latest version. 

![EC914DD0-FB37-4918-9B0A-57452A2A6091](https://user-images.githubusercontent.com/92247322/158769455-aff971fa-9d7b-4c6a-8ecc-c7e292f12e87.png)
![A654ABAE-B727-4FB1-B8AE-9B0F0F08431C](https://user-images.githubusercontent.com/92247322/158769470-51684bb9-290d-4716-b6ec-d38c1cd8380b.png)
![8366011D-3D48-4A3A-8E98-19447AE6553A](https://user-images.githubusercontent.com/92247322/158769477-0f8a7977-094a-43c5-a209-cfa8552b861d.png)
![AA970FBD-C7E3-4583-A0CD-BA1ADF4E5DB0](https://user-images.githubusercontent.com/92247322/158769485-b2563e0d-5d79-44f1-bbfb-af7877c5d6ef.png)
![36408557-C5F9-404B-960A-BE3E9E69286A](https://user-images.githubusercontent.com/92247322/158769490-80ddf1ff-f0b0-488e-a1f5-c9a6a4c6deae.png)
![7F2B5AEE-D095-4255-B2CB-AA1FD7D5E9EB](https://user-images.githubusercontent.com/92247322/158769493-6158febb-9ea5-4963-972e-ed12cb51da44.png)
![696D1CCE-5C63-47DB-BBAC-04E1F43AD759](https://user-images.githubusercontent.com/92247322/158769496-cc63d83d-939d-47e8-ad0a-5bf835d76bc2.png)

**Comment by Oksydan** [comment]
Hi @slawekmoskal 
I was able to reproduce an error. 
It is related to recent changes in safari browser. 
I will investigate it and fix it.

**Comment by Oksydan** [comment]
Hi @slawekmoskal issue has been fixed on dev branch and will be available with next release. 
You can implement it right now inside your theme https://github.com/Oksydan/modern-prestashop-starter-theme/commit/117eefc1f210e9e76408f8577056cf1faacbddde

I am closing this issue for now. If you find any problem create new issue.
