### ISSUE TITLE
Unable to have a correct setup on Windows10 / WSL

### ISSUE THREAD

**Issue by Zicguy** [Oksydan/modern-prestashop-starter-theme#85]
Hi !

First of all, thanks for your work!
I spent many hours to setup your dev theme under Windows 10 / WSL without any success. Main blocking points are:
- the automatically launch of the webserver
- the WS socket that produces many errors into the brower console

Is it possible to deactivates both?

My local webserver is apache2 under WSL (Debian10). I reach local prestashop under vhost (e.g. https://dev.prestashop.fr) from Windows 10. So, in my opinion, launch automatically a webserver must be an option.

Do you have any advise on how to make your dev theme works on Windows 10 / WSL?

Many thanks!

**Comment by Oksydan** [comment]
HI @Zicguy,
Unfortunately I am not familiar with WSL. 
Can you post error from your console?
What is your node version? 

Webpack dev server is required for HMR to work. 
I probably will make watch command w/o webpack dev server in next major version.

**Comment by Oksydan** [comment]
Sine this issue is inactive for 2 month I will close it.
Feel free to open new one.
