### ISSUE TITLE
PS 1.7.8.3 - unknown tag 'generateImagesSources' - Custom Module Order Page

### ISSUE THREAD

**Issue by Alan3k** [Oksydan/modern-prestashop-starter-theme#86]
Hello,

At first thank you for your work with creating this theme.

I have issue similar to this topic: 
https://github.com/Oksydan/modern-prestashop-starter-theme/issues/39

If i'm using custom module for order page there is issue with this tag "generateImagesSources".

Module which i'm using is "SZYBKIE ZAKUPY PRO DLA PRESTASHOP 1.7.X" from PrestaDev. I have also try with other module One Page Checkout from Knowband and it's also not working.

You can see error message from debug on attachment.

![error](https://user-images.githubusercontent.com/29299511/161427583-7d71c7c9-1311-4267-9d93-8ea74b1cd124.jpg)

Do you have any suggestions how could I fix that?

PHP: 7.4

**Comment by JanGorzycki** [comment]
unsubscribe

niedz., 3 kwi 2022, 14:15 użytkownik Alan3k ***@***.***>
napisał:

**Comment by Oksydan** [comment]
Hi @Alan3k,
are those modules using `hookActionDispatcher` hook and exit somewhere inside those hooks??
If they do you will have to rename `hookActionDispatcher` to `actionDispatcherBefore` and hook `is_themecore` to this hook. 
It should resolve all of your problems.
There is [v2](https://github.com/Oksydan/is_themecore/tree/2.0.0) branch for `is_themecore` with complete module refacto and new features. I will add this fix also for new version. 

Check and please come back to tell me if your problem has been resolved.

**Comment by Alan3k** [comment]
You are great!

Exactly, this custom module is using hookActionDispatcher. When I moved is_themecore to hookActionDispatcherBefore, order page is working well.

So issue is solved.

I'm really glad for your help and really quick answer. :)

Ps. I will check new version of your module.

**Comment by Oksydan** [comment]
@Alan3k  don't use v2 of is_themecore yet, it isn't finished. I will be officially released with 3.0 version of starer.

**Comment by Alan3k** [comment]
Don't worry, I will wait for official release and use it in future projects. Once again, thanks for your work. :)
