### ISSUE TITLE
Module/Addon install error 

### ISSUE THREAD

**Issue by szobonyatomi** [Oksydan/modern-prestashop-starter-theme#92]
Hello, 

After the installation not able to choose and change to your theme in the BO, it gives error 
![Screenshot 2022-06-07 at 22 24 01](https://user-images.githubusercontent.com/29607032/172475993-ebf9237e-9ea2-4f62-9660-bdd3cd482f1c.png)

But the FO looks almost good, only the image slider not showing

![Screenshot 2022-06-07 at 22 24 14](https://user-images.githubusercontent.com/29607032/172476121-b446116c-4733-447b-957f-5a9323867b8a.png)

thank you for any advice

t

**Comment by Oksydan** [comment]
Hi @szobonyatomi,
you have to download required modules and place them inside modules directory [how to](https://github.com/Oksydan/modern-prestashop-starter-theme#prerequisites). If release is provided inside module download it via releases (all modules should be available) otherwise clone it.

**Comment by szobonyatomi** [comment]
it had been done earlier, followed by the 'how to', of course, 
but it doesn't works
![Screenshot 2022-06-08 at 00 36 27](https://user-images.githubusercontent.com/29607032/172494662-ec56f0cd-c5b3-4788-abf5-e7b496415d0f.png)

**Comment by Oksydan** [comment]
Lukę you can ser, module directory name contains branch name -main. You  have to rename it to match main pho file. Btw remember to downoload is_themecore module from release otherwise you will have to run composer install inside module directory.

**Comment by Oksydan** [comment]
Since you didn't response in 14 days I am going to close this issue.
If you find any problem, feel free to open new one.
