### ISSUE TITLE
Issue with facetted search

### ISSUE THREAD

**Issue by Kandax86** [Oksydan/modern-prestashop-starter-theme#95]
Hi,

there are issues with filters in category.

If you change number of product per page or sort option and filter after, it reset the configuration of sort and number of products.
If you filter on a feature and you filter on price right after, it reset the previous filters and keep only the price.

Regards,

Cédric

**Comment by Oksydan** [comment]
HI @Kandax86,

thank you for opening an issue.
I was able to reproduce problem but I am not sure if that isn't related to faceted module itself not starter.
I will investigate it with clear prestashop installation and come back with feedback.

**Comment by Kandax86** [comment]
Hi thanks for your answer, I already checked with an out of the box fresh 1.7 and filters are well merged between price and features (except there is no number of products dropdown in classic 1.7)

**Comment by Oksydan** [comment]
Hi @Kandax86,
problem has been fixed. It will be released with next minor version but you can fix it right now in your theme https://github.com/Oksydan/modern-prestashop-starter-theme/commit/803cde2a8ffa8129d0004d493de6346fe14975b8.

**Comment by Kandax86** [comment]
Hi 
thats great now thank you for your feeback !

**Comment by Oksydan** [comment]
New version has been released. I am closing this issue.
Thank you for your report.
