### ISSUE TITLE
Notice: Undefined index: allow_oops

### ISSUE THREAD

**Issue by design4VIP** [Oksydan/modern-prestashop-starter-theme#96]
![image](https://user-images.githubusercontent.com/107250228/173040959-8e146413-6e46-49c6-bd03-f05e2d84c979.png)

PS 1.7.8.6 
FRONT przy wejściu do produktu z brakiem na stanie

**Comment by design4VIP** [comment]
literówka 'oops' -> 'oosp' 

![image](https://user-images.githubusercontent.com/107250228/173042291-2fa03115-7465-4bf9-8332-1dd12aa16f08.png)

**Comment by Oksydan** [comment]
Hi @design4VIP,

issue has been fixed with version 2.1.0 of is_themecore module that just has been released.
