### ISSUE TITLE
Smart cache issue

### ISSUE THREAD

**Issue by sparh** [Oksydan/modern-prestashop-starter-theme#98]
Hello
"Multiple entry point for webpack, files separated per view. There are 4 output js/css files theme, product, checkout, listing and you are able to add more with ease. If you need rich cms pages with a lot of styles included in it. You don't have to include them everywhere with theme output file. You are able to create another entry e.g. cms and just modify assets.yml file to include new assets file."

This is a great feature to improve page loading time but when we activate "Smart cache" in Performance tab the custom css and js files are not included anymore.

Is there a way to activate Smart Cache and keep product/checkout and listing css and js files ?

**Comment by Oksydan** [comment]
Hi @sparh 

It isn't about smarty cache but CCC feature. If you will enable it will bundle all css/js file into one depending on controller. (multiple bundles for multiple controllers). I am not able to separate those files from that bundle w/o modifying prestashop core.

**Comment by Oksydan** [comment]
Hi @sparh,

I am closing this issue since it has been resolved.
