### ISSUE TITLE
HTML default numbered list <ol> - CMS pages

### ISSUE THREAD

**Issue by przemokon** [Oksydan/modern-prestashop-starter-theme#99]
Hello,

I found that in CMS pages list-style is overwritten via inherit property, and because of this default numbered list is rendering as unordered list.

Firefox
![image](https://user-images.githubusercontent.com/26924707/176180321-aac07ed3-fd9b-4e5c-9376-a1595cee1ea1.png)

Chrome
![image](https://user-images.githubusercontent.com/26924707/176180391-a4985869-a943-469d-b2dc-9d3125a5a623.png)

Tested on demo site

**Comment by Oksydan** [comment]
Hi @przemokon,
thank you for creating an issue.
I was able to reproduce it, I will inform you when it will be fixed.

**Comment by Oksydan** [comment]
Hi @przemokon,

problem has been [fixed](https://github.com/Oksydan/modern-prestashop-starter-theme/commit/a367b5cd794db26d3513879eb7a9dc74f398c8cb) and will be released with next version 2.2.0.
Thank you for your report.

**Comment by Oksydan** [comment]
New version has been released. I am closing this issue.
Thank you for your report.
